name: CI

# Controls when the workflow will run
on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt install clang-format-12

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Check codestyle
        run: git ls-files *.{cpp,hpp} | xargs clang-format-12 -i && git diff --exit-code

      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy 

      - name: Update submodules
        run: git submodule init && git submodule update

      - name: Build application
        run: ./build.sh

      - name: Run tests
        run: ctest --test-dir build/debug/ --output-on-failure && ctest --test-dir build/release/ --output-on-failure

